In [1]:
import glob 
import re
import json
import pandas as pd 
import os

In [2]:


# data_column is read by a file .json
def get_column_names(data_column, name_object):
    set_column = data_column[name_object] 
    set_column = sorted( set_column , key = lambda col: col['column_position'] )
    return [ column['column_name'] for column in set_column ]

def process_file(source_path , target_path):
    # read file json from source, which include columns  
    path_data_schemas = source_path + '/schemas.json' 
    json_data_schemas = json.load( open(path_data_schemas) )
    print(json_data_schemas) 
    os.makedirs(f'{target_path}',exist_ok= True)
    
    # for name_table in json_data_schemas.keys():
    #     os.remove(f'{target_path}/{name_table}') 
    
    for name_table in json_data_schemas.keys():
        print(name_table)
        table_files = glob.glob(f'{source_path}/{name_table}/*') 
        for table_file in table_files: 
            df_table_data = pd.read_csv(table_file, names = get_column_names(json_data_schemas,name_table) ) 
            print(df_table_data)
            
            #json_table have type of string. lines = true -> \n 
            json_table = df_table_data.to_json(f'{target_path}/{name_table}.json', orient = 'records' , lines= True) 
            continue
            
            # json_table = df_table_data.to_json( orient= 'records' , lines= True) 
            # print('json_table  : ' , type(json_table))
            # print(json_table)
            # with open(f'{target_path}/{name_table}.json', "w") as json_file:
            #     json_file.write( json_table)
            #     json.dump(json_table ,json_file , indent= 4)

        #os.makedirs(f'{target}/{name_table}' )

In [3]:
source = 'data/retail_db' 
target = 'data/retail_db_json'
process_file( source , target )

{'departments': [{'column_name': 'department_id', 'data_type': 'integer', 'column_position': 1}, {'column_name': 'department_name', 'data_type': 'string', 'column_position': 2}], 'categories': [{'column_name': 'category_id', 'data_type': 'integer', 'column_position': 1}, {'column_name': 'category_department_id', 'data_type': 'integer', 'column_position': 2}, {'column_name': 'category_name', 'data_type': 'string', 'column_position': 3}], 'orders': [{'column_name': 'order_id', 'data_type': 'integer', 'column_position': 1}, {'column_name': 'order_date', 'data_type': 'string', 'column_position': 2}, {'column_name': 'order_customer_id', 'data_type': 'timestamp', 'column_position': 3}, {'column_name': 'order_status', 'data_type': 'string', 'column_position': 4}], 'products': [{'column_name': 'product_id', 'data_type': 'integer', 'column_position': 1}, {'column_name': 'product_cateogry_id', 'data_type': 'integer', 'column_position': 2}, {'column_name': 'product_name', 'data_type': '', 'column_position': 3}, {'column_name': 'product_description', 'data_type': 'string', 'column_position': 4}, {'column_name': 'product_price', 'data_type': 'float', 'column_position': 5}, {'column_name': 'product_image', 'data_type': 'string', 'column_position': 6}], 'customers': [{'column_name': 'customer_id', 'data_type': 'integer', 'column_position': 1}, {'column_name': 'customer_fname', 'data_type': 'string', 'column_position': 2}, {'column_name': 'customer_lname', 'data_type': 'string', 'column_position': 3}, {'column_name': 'customer_email', 'data_type': 'string', 'column_position': 4}, {'column_name': 'customer_password', 'data_type': 'string', 'column_position': 5}, {'column_name': 'customer_street', 'data_type': 'string', 'column_position': 6}, {'column_name': 'customer_city', 'data_type': 'string', 'column_position': 7}, {'column_name': 'customer_state', 'data_type': 'string', 'column_position': 8}, {'column_name': 'customer_zipcode', 'data_type': 'integer', 'column_position': 9}], 'order_items': [{'column_name': 'order_item_id', 'data_type': 'integer', 'column_position': 1}, {'column_name': 'order_item_order_id', 'data_type': 'integer', 'column_position': 2}, {'column_name': 'order_item_product_id', 'data_type': 'integer', 'column_position': 3}, {'column_name': 'order_item_quantity', 'data_type': 'integer', 'column_position': 4}, {'column_name': 'order_item_subtotal', 'data_type': 'float', 'column_position': 5}, {'column_name': 'order_item_product_price', 'data_type': 'float', 'column_position': 6}]}
departments
   department_id department_name
0              2         Fitness
1              3        Footwear
2              4         Apparel
3              5            Golf
4              6        Outdoors
5              7        Fan Shop
categories
    category_id  category_department_id         category_name
0             1                       2              Football
1             2                       2                Soccer
2             3                       2   Baseball & Softball
3             4                       2            Basketball
4             5                       2              Lacrosse
5             6                       2      Tennis & Racquet
6             7                       2                Hockey
7             8                       2           More Sports
8             9                       3      Cardio Equipment
9            10                       3     Strength Training
10           11                       3   Fitness Accessories
11           12                       3          Boxing & MMA
12           13                       3           Electronics
13           14                       3        Yoga & Pilates
14           15                       3     Training by Sport
15           16                       3       As Seen on  TV!
16           17                       4                Cleats
17           18                       4        Men's Footwear
18           19                       4      Women's Footwear
19           20                       4        Kids' Footwear
20           21                       4        Featured Shops
21           22                       4           Accessories
22           23                       5         Men's Apparel
23           24                       5       Women's Apparel
24           25                       5         Boys' Apparel
25           26                       5        Girls' Apparel
26           27                       5           Accessories
27           28                       5            Top Brands
28           29                       5         Shop By Sport
29           30                       6      Men's Golf Clubs
30           31                       6    Women's Golf Clubs
31           32                       6          Golf Apparel
32           33                       6            Golf Shoes
33           34                       6     Golf Bags & Carts
34           35                       6           Golf Gloves
35           36                       6            Golf Balls
36           37                       6           Electronics
37           38                       6      Kids' Golf Clubs
38           39                       6             Team Shop
39           40                       6           Accessories
40           41                       6              Trade-In
41           42                       7     Bike & Skate Shop
42           43                       7      Camping & Hiking
43           44                       7    Hunting & Shooting
44           45                       7               Fishing
45           46                       7  Indoor/Outdoor Games
46           47                       7               Boating
47           48                       7          Water Sports
48           49                       8                   MLB
49           50                       8                   NFL
50           51                       8                   NHL
51           52                       8                   NBA
52           53                       8                  NCAA
53           54                       8                   MLS
54           55                       8  International Soccer
55           56                       8        World Cup Shop
56           57                       8           MLB Players
57           58                       8           NFL Players
orders
       order_id             order_date  order_customer_id     order_status
0             1  2013-07-25 00:00:00.0              11599           CLOSED
1             2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
2             3  2013-07-25 00:00:00.0              12111         COMPLETE
3             4  2013-07-25 00:00:00.0               8827           CLOSED
4             5  2013-07-25 00:00:00.0              11318         COMPLETE
...         ...                    ...                ...              ...
68878     68879  2014-07-09 00:00:00.0                778         COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117         COMPLETE
68880     68881  2014-07-19 00:00:00.0               2518  PENDING_PAYMENT
68881     68882  2014-07-22 00:00:00.0              10000          ON_HOLD
68882     68883  2014-07-23 00:00:00.0               5533         COMPLETE

[68883 rows x 4 columns]
products
      product_id  product_cateogry_id  \
0              1                    2
1              2                    2
2              3                    2
3              4                    2
4              5                    2
...          ...                  ...
1340        1341                   59
1341        1342                   59
1342        1343                   59
1343        1344                   59
1344        1345                   59

                                       product_name  product_description  \
0     Quest Q64 10 FT. x 10 FT. Slant Leg Instant U                  NaN
1     Under Armour Men's Highlight MC Football Clea                  NaN
2     Under Armour Men's Renegade D Mid Football Cl                  NaN
3     Under Armour Men's Renegade D Mid Football Cl                  NaN
4     Riddell Youth Revolution Speed Custom Footbal                  NaN
...                                             ...                  ...
1340  Nike Women's Cleveland Browns Johnny Football                  NaN
1341  Nike Men's St. Louis Rams Michael Sam #96 Nam                  NaN
1342  Nike Men's Home Game Jersey St. Louis Rams Mi                  NaN
1343  Nike Men's Home Game Jersey St. Louis Rams Aa                  NaN
1344  Nike Men's Home Game Jersey St. Louis Rams Gr                  NaN

      product_price                                      product_image
0             59.98  http://images.acmesports.sports/Quest+Q64+10+F...
1            129.99  http://images.acmesports.sports/Under+Armour+M...
2             89.99  http://images.acmesports.sports/Under+Armour+M...
3             89.99  http://images.acmesports.sports/Under+Armour+M...
4            199.99  http://images.acmesports.sports/Riddell+Youth+...
...             ...                                                ...
1340          34.00  http://images.acmesports.sports/Nike+Women%27s...
1341          32.00  http://images.acmesports.sports/Nike+Men%27s+S...
1342         100.00  http://images.acmesports.sports/Nike+Men%27s+H...
1343         100.00  http://images.acmesports.sports/Nike+Men%27s+H...
1344         100.00  http://images.acmesports.sports/Nike+Men%27s+H...

[1345 rows x 6 columns]
customers
       customer_id customer_fname customer_lname customer_email  \
0                1        Richard      Hernandez      XXXXXXXXX
1                2           Mary        Barrett      XXXXXXXXX
2                3            Ann          Smith      XXXXXXXXX
3                4           Mary          Jones      XXXXXXXXX
4                5         Robert         Hudson      XXXXXXXXX
...            ...            ...            ...            ...
12430        12431           Mary           Rios      XXXXXXXXX
12431        12432         Angela          Smith      XXXXXXXXX
12432        12433       Benjamin         Garcia      XXXXXXXXX
12433        12434           Mary          Mills      XXXXXXXXX
12434        12435          Laura         Horton      XXXXXXXXX

      customer_password             customer_street customer_city  \
0             XXXXXXXXX          6303 Heather Plaza   Brownsville
1             XXXXXXXXX     9526 Noble Embers Ridge     Littleton
2             XXXXXXXXX      3422 Blue Pioneer Bend        Caguas
3             XXXXXXXXX          8324 Little Common    San Marcos
4             XXXXXXXXX      10 Crystal River Mall         Caguas
...                 ...                         ...           ...
12430         XXXXXXXXX           1221 Cinder Pines       Kaneohe
12431         XXXXXXXXX  1525 Jagged Barn Highlands        Caguas
12432         XXXXXXXXX    5459 Noble Brook Landing     Levittown
12433         XXXXXXXXX        9720 Colonial Parade        Caguas
12434         XXXXXXXXX            5736 Honey Downs   Summerville

      customer_state  customer_zipcode
0                 TX             78521
1                 CO             80126
2                 PR               725
3                 CA             92069
4                 PR               725
...              ...               ...
12430             HI             96744
12431             PR               725
12432             NY             11756
12433             PR               725
12434             SC             29483

[12435 rows x 9 columns]
order_items
        order_item_id  order_item_order_id  order_item_product_id  \
0                   1                    1                    957
1                   2                    2                   1073
2                   3                    2                    502
3                   4                    2                    403
4                   5                    4                    897
...               ...                  ...                    ...
164461         172194                68881                    403
164462         172195                68882                    365
164463         172196                68882                    502
164464         172197                68883                    208
164465         172198                68883                    502

        order_item_quantity  order_item_subtotal  order_item_product_price
0                         1               299.98                    299.98
1                         1               199.99                    199.99
2                         5               250.00                     50.00
3                         1               129.99                    129.99
4                         2                49.98                     24.99
...                     ...                  ...                       ...
164461                    1               129.99                    129.99
164462                    1                59.99                     59.99
164463                    1                50.00                     50.00
164464                    1              1999.99                   1999.99
164465                    3               150.00                     50.00

[164466 rows x 6 columns]

In [4]:

# source_data = './' + 'data/retail_db/*/*' 
# path_data_column = r'D:\codes_python_in_visual_studio_code\data\retail_db\schemas.json' 
# json_column = json.load( open(path_data_column) )


# for file in glob.glob(source_data) :
#     print(file )
#     file_path_list = re.split('[/\\\]', file) 
#     print(file_path_list) 
#     column_set  = get_column_names(json_column, file_path_list[-2])
#     print(column_set)
    
#     # read  data from column_set and rows of records
#     data = pd.read_csv( file , names = column_set ) 
#     # print(data.keys()) 
#     # for x in data['category_id'] : 
#     #     print(x)